### ISSUE TITLE
buckaroo update throws null pointer exception

### ISSUE THREAD

**Issue by mc-allen** [LoopPerfect/buckaroo#144] opened 2017-12-20 17:58 UTC
## Description
I am trying to build and use buck from source, on OS X 10.12.6, branch release/1.3.1

I was able to build it, using buck (also built from source, version 1531ce73923370895e32a41833a015b486d4ff51)

If I run 

```
java -jar buckaroo-cli.jar update
```

I get 

```
updating cookbooks:
Error!
java.lang.NullPointerException
Get help at https://github.com/loopperfect/buckaroo/issues
The stacktrace was written to buckaroo-stacktrace.log.
```

and stack trace [buckaroo-stacktrace.log](https://github.com/LoopPerfect/buckaroo/files/1576560/buckaroo-stacktrace.log)

## Expected Behavior

No null pointer exception :)

## Actual Behavior

Code goes explodey.

## Possible Fix

It seems like the code on src/main/java/com/loopperfect/buckaroo/tasks/UpdateTasks.java:88 expects pullResult.getMergeResult() to never be null, but it is in my case, for whatever reason. I tried to dig into the jgit docs but it wasn't obvious what circumstance would cause a null pointer. I think that in reality, the pull on buckaroo-recipes finds no new commits, so it's a no-op.

If I add the null check, the code ceases to crash, but I don't know if there are other negative side effects of doing this.

```
~   2                     if (pullResult.getMergeResult() != null) {
+   1                       emitter.onNext(Notification.of(pullResult.getMergeResult().toString()+" "));
+ 90                      }
```

## Steps to Reproduce

Build buckaroo release/1.3.1 from source, and run 

```
java -jar buckaroo-cli.jar update
```

## Your Environment
* Version used: release/1.3.1
* Operating System and Architecture: OS X 10.12.6

**Comment by njlr** [comment] 2018-10-16 08:41
I was unable to reproduce this, even when the cookbooks did not require an update.

**Comment by njlr** [comment] 2019-01-07 15:31
Closing this since it is specific to Buckaroo 1.x

**Closed by njlr** 2019-01-07 15:31 UTC
